services:
  db:
    container_name: postgresql
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "9000:80"
    networks:
      - pg-network
    depends_on:
      - db

  api:
    build: .
    container_name: api
    environment:
      - DB_URL=jdbc:postgresql://db:5432/${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - GMAIL_USERNAME=${GMAIL}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - pg-network
    depends_on:
      - db

volumes:
  db-data:
  pgadmin-data:

networks:
  pg-network: