spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/minha_feira
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate

server:
  error:
    include-message: always

logging:
  patterns:
    console: "%d{HH:mm:ss.SSS} [thread] %-5level %logger{36} - %msg%n"
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE